
model: gmm
dataset_name: emodb
dataset_path: '/mnt/E/dataset/emodb/'
class_labels: ["anger", "boredom", "disgust", "neutral", "fear", "happiness", "sadness"]

pickle_path: './Data/train/emodb/'
models_path: './Models/emodb/'