model: gmm
dataset_name: emodb
dataset_path: '/mnt/E/dataset/emodb/'
class_labels: ["anger", "boredom", "disgust", "neutral", "fear", "happiness", "sadness"]

pickle_path: 'Data/train/emodb/'
models_path: 'Models/emodb/'
res_path: 'Result/emodb/'


# component_num:7    75.68%
component_num: [5, 7 ,10, 16, 32, 64 , 128, 256, 512]