model: lstm

# 数据集
dataset: emodb
data_path: /home/victor/Project/Speech-Emotion-Recognition/SER-GMM/Data/  # 数据集路径
# class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]  # 情感标签
# class_labels: ["positive", "negative", "neutral"]
# class_labels: ["angry", "sad", "neutral", "disgust", "happy", "fear", "surprise", "calm"]
# class_labels: ['angry', 'sad', 'happy', 'frustration', 'neutral', 'surprise']
#### emodb ####
class_labels: ['angry', 'sad', 'happy', 'disgust', 'neutral', 'fear', 'boredom']
# 特征存储
feature_path: features/6-category/  # 特征存储路径
train_feature_path_opensmile: features/6-category/train_opensmile_emodb.csv  # 训练特征存储路径（Opensmile）
predict_feature_path_opensmile: features/6-category/test_opensmile_emodb.csv  # 预测特征存储路径（Opensmile）
train_feature_path_librosa: features/6-category/train_librosa_emodb.p  # 训练特征存储路径（librosa）
predict_feature_path_librosa: features/6-category/test_librosa_emodb.p  # 预测特征存储路径（librosa）

# 特征提取方式
feature_method: o  # 'o': opensmile, 'l': librosa

# Opensmile 配置，只在 'feature_method: o' 时 需要设置
opensmile_path: /home/victor/Project/util/opensmile/build/progsrc/smilextract # Opensmile 安装路径
opensmile_config: /home/victor/Project/util/opensmile/config/is09-13/IS10_paraling.conf # Opensmile 标准特征集
# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
#checkpoint_name: LSTM_OPENSMILE_IS10  # checkpoint 文件名
checkpoint_name: LSTM_OPENSMILE_EMODB
# 训练参数
epochs: 20  # 训练 epoch 数
batch_size: 128  # 批大小
lr: 0.0015  # 学习率

# 模型参数
rnn_size: 128  # LSTM 隐藏层大小
hidden_size: 32
dropout: 0.5