
# 数据集
dataset: emodb
data_path: /mnt/E/dataset # 数据集路径
 
## CASIA ###
#class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]
### NNIME ###
# class_labels: ["angry", "frustration", "happy", "neutral", "sad", "surprise"]  # 情感标签
### RAVDESS ###
#class_labels: ["angry", "sad", "neutral", "disgust", "happy", "fear", "surprise", "calm"]
#### emodb ####
class_labels: ['angry', 'sad', 'happy', 'disgust', 'neutral', 'fear', 'boredom']


